version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t nodejs-demo:latest .
      - docker tag nodejs-demo:latest 406524075996.dkr.ecr.us-east-1.amazonaws.com/nodejs-demo:latest
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 406524075996.dkr.ecr.us-east-1.amazonaws.com/nodejs-demo:latest